[project]
name = "wagtail-return"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pip>=25.0.1",
    "wagtail>=6.4.1",
]
